#!/usr/bin/env python3
"""Regenerate personas/ROSTER.md from persona-card frontmatter.

The ROSTER is what the /challenge Orchestrator loads to route a problem to the right
grounded experts and to assemble a council that disagrees. Keep it compact.

No deps. Run: python3 build-personas-roster.py
"""
import re
from pathlib import Path

PD = Path(__file__).parent / "personas"


def parse_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return {}
    fm = {}
    for line in m.group(1).splitlines():
        m2 = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if not m2:
            continue
        key, val = m2.group(1), m2.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            fm[key] = [x.strip().strip('"\'') for x in val[1:-1].split(",") if x.strip()]
        elif val:
            fm[key] = val.strip('"\'')
    return fm


people = []
for p in sorted(PD.glob("*.md")):
    if p.name in ("PERSONA_SCHEMA.md", "ROSTER.md"):
        continue
    fm = parse_frontmatter(p.read_text())
    if fm:
        fm["_slug"] = p.stem
        people.append(fm)

valid_slugs = {p["_slug"] for p in people}

# Build deduped tension pairs
pairs = set()
warnings = []
for p in people:
    for other in p.get("disagrees_with", []):
        if other not in valid_slugs:
            warnings.append(f"{p['_slug']} disagrees_with unknown slug '{other}'")
            continue
        pairs.add(tuple(sorted((p["_slug"], other))))

lines = []
lines.append("# Council Roster")
lines.append("")
lines.append(f"_{len(people)} grounded personas, built from `frameworks/` cards. "
             "Auto-generated by `build-personas-roster.py` — do not edit by hand._")
lines.append("")
lines.append("The `/challenge` Orchestrator loads this to (1) match a problem to experts by "
             "**keywords/domains**, and (2) assemble a council that **disagrees** using the tension map.")
lines.append("")
lines.append("## Personas")
lines.append("")
lines.append("| Slug | Seat | Domains | Match keywords | Clashes with | Conf |")
lines.append("|---|---|---|---|---|---|")
for p in sorted(people, key=lambda x: x["_slug"]):
    seat = p.get("seat", "—")
    dom = ", ".join(p.get("domains", [])) or "—"
    kw = ", ".join(p.get("keywords", [])) or "—"
    clash = ", ".join(p.get("disagrees_with", [])) or "—"
    conf = p.get("confidence", "—")
    name = p.get("persona", p["_slug"])
    lines.append(f"| **{p['_slug']}** ({name}) | {seat} | {dom} | {kw} | {clash} | {conf} |")

lines.append("")
lines.append("## Tension map (productive disagreements)")
lines.append("")
lines.append("Pair these when a topic spans both — the council argues instead of agreeing.")
lines.append("")
for a, b in sorted(pairs):
    lines.append(f"- **{a} ↔ {b}**")
lines.append("")

if warnings:
    lines.append("## ⚠ Warnings")
    lines.append("")
    for w in warnings:
        lines.append(f"- {w}")
    lines.append("")

(PD / "ROSTER.md").write_text("\n".join(lines))
print(f"Wrote ROSTER.md — {len(people)} personas, {len(pairs)} tension pairs, {len(warnings)} warnings.")
for w in warnings:
    print("  ⚠", w)
