#!/usr/bin/env python3
"""Regenerate frameworks/INDEX.md from the frontmatter of every framework card.

Emits two views:
  1. Roster   — framework / owner / domain / confidence, alphabetical by owner.
  2. Reverse  — skill -> the framework cards that feed it (how skills cite the library).

No deps. Run: python3 build-frameworks-index.py
"""
import re
from pathlib import Path

FW = Path(__file__).parent / "frameworks"


def parse_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---", text, re.DOTALL)
    if not m:
        return {}
    fm, block = {}, m.group(1)
    for line in block.splitlines():
        m2 = re.match(r"^([a-z_]+):\s*(.*)$", line)
        if not m2:
            continue
        key, val = m2.group(1), m2.group(2).strip()
        if val.startswith("[") and val.endswith("]"):
            items = [x.strip().strip('"\'') for x in val[1:-1].split(",") if x.strip()]
            fm[key] = items
        elif val:
            fm[key] = val.strip('"\'')
    return fm


cards = []
for p in sorted(FW.glob("*.md")):
    if p.name in ("SCHEMA.md", "INDEX.md"):
        continue
    fm = parse_frontmatter(p.read_text())
    if not fm:
        continue
    fm["slug"] = p.stem
    cards.append(fm)

# Reverse index: skill -> [(framework, slug)]
skill_map = {}
for c in cards:
    for s in c.get("feeds_skills", []):
        skill_map.setdefault(s, []).append((c.get("framework", c["slug"]), c["slug"]))

lines = []
lines.append("# Frameworks Index")
lines.append("")
lines.append(f"_{len(cards)} grounded framework cards, extracted from Lenny's Podcast transcripts. "
             "Auto-generated by `build-frameworks-index.py` — do not edit by hand._")
lines.append("")
lines.append("## Roster")
lines.append("")
lines.append("| Owner | Framework | Domain | Confidence |")
lines.append("|---|---|---|---|")
for c in sorted(cards, key=lambda c: c.get("owner", "").split()[-1].lower() if c.get("owner") else ""):
    owner = c.get("owner", "—")
    fw = f"[{c.get('framework', c['slug'])}](frameworks/{c['slug']}.md)"
    dom = ", ".join(c.get("domain", [])) or "—"
    conf = c.get("confidence", "—")
    lines.append(f"| {owner} | {fw} | {dom} | {conf} |")

lines.append("")
lines.append("## Reverse index — which frameworks feed which of your skills")
lines.append("")
for skill in sorted(skill_map):
    refs = ", ".join(f"[{name}](frameworks/{slug}.md)" for name, slug in sorted(skill_map[skill]))
    lines.append(f"- **/{skill}** — {refs}")
lines.append("")

(FW.parent / "INDEX.md").write_text("\n".join(lines))
print(f"Wrote INDEX.md — {len(cards)} cards, {len(skill_map)} skills mapped.")
